export const GET_TUTORS_START = 'GET_TUTORS_START';
export const GET_TUTORS_SUCCESS = 'GET_TUTORS_SUCCESS';
export const GET_TUTORS_FAILURE = 'GET_TUTORS_FAILURE';
export const GET_TUTORS_END = 'GET_TUTORS_END';